# Basic test configuration for the VL6180X custom component
# Use this to verify your hardware connection and basic distance readings.

esphome:
  name: vl6180x-basic-test
  friendly_name: VL6180X Basic Test

# Link to your custom component on GitHub
external_components:
  - source: github://adynis/esphome-vl6180x-pololu@v1.0.0
    components: [ vl6180x_pololu ]

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging - use DEBUG level to see detailed hardware diagnostics
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "w2lj73t5aWlyVrROEXiH7eXynJliitveO0Bet0SH910="

ota:
  - platform: esphome
    password: "8e6c1cf89046a1566a53e3d280c4e2b2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Fallback AP for initial configuration
  ap:
    ssid: "VL6180X-Basic-Test"
    password: "DLgJlZAOCUGI"

captive_portal:

sensor:
  - platform: vl6180x_pololu
    sda_pin: 23 # Connect to SDA pin of your VL6180X
    scl_pin: 22 # Connect to SCL pin of your VL6180X
    # address: 0x29 # Optional, defaults to 0x29
    
    # DISTANCE SENSOR SECTION
    distance:
      name: "Distance"
      update_interval: 500ms
      # NOTE: Generic clones often require an offset (e.g., +50mm)
      offset: 50.0 # optional, defaults to 0
      filters:
        # Median filter stabilizes readings by removing outliers
        - median:
            window_size: 5
            send_every: 1
            
    distance_error_code:
      name: "Distance Error Code"

    # AMBIENT LIGHT SENSOR (ALS) SECTION
    # NOTE: Commented out because some generic VL6180X modules have faulty light sensors.
    # Uncomment below if your hardware supports ALS.
    
    # ambient_light:
    #   name: "Illuminance"
    #   update_interval: 5s
    #   gain: 20 # Available gains: 1, 10, 20, 40 (20 is standard)
      
    # ambient_light_error_code:
    #   name: "ALS Error Code"



